
all:
	g++ -O3 -std=c++17 -DSCDEKKERS  main.cpp -lpthread -o scdekker
	g++ -O3 -std=c++17 -DRDEKKERS   main.cpp -lpthread -o rdekkers
	g++ -O3 -std=c++17 -DTSODEKKERS main.cpp -lpthread -o tsodekkers
